services:
    strapi:
        container_name: strapi
        build: .
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_HOST: strapiDB
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
            APP_KEYS: ${APP_KEYS}
            NODE_ENV: ${NODE_ENV}
        ports:
            - "1337:1337"
        volumes:
            # bind mount solo di codice e config
            - ./config:/opt/app/config
            - ./src:/opt/app/src
            - ./public/uploads:/opt/app/public/uploads
            # monta lockfile e manifest, se vuoi limitare le rebuild di dipendenze
            - ./package.json:/opt/app/package.json
            - ./yarn.lock:/opt/app/yarn.lock
        command: npm run develop
        networks:
            - strapi
        depends_on:
            - strapiDB

    strapiDB:
        container_name: strapiDB
        image: postgres:16.0-alpine
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - "5432:5432"
        volumes:
            - strapi-data:/var/lib/postgresql/data
        networks:
            - strapi

volumes:
    strapi-data:

networks:
    strapi:
        driver: bridge
